/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/AsideMenu.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAlarmFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconAlarmFill']
    IconAppOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconAppOutline']
    IconCirclePlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconCirclePlusOutline']
    IconDeleteOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconDeleteOutline']
    IconEmailFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconEmailFill']
    IconPlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconPlusOutline']
    IconSettingsOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconSettingsOutline']
    IconSunOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconSunOutline']
    Line: typeof import('./src/components/Echarts/line.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagBar: typeof import('./src/components/TagBar.vue')['default']
    YkAvatar: typeof import('@yike-design/ui')['YkAvatar']
    YkButton: typeof import('@yike-design/ui')['YkButton']
    YkDivider: typeof import('@yike-design/ui')['YkDivider']
    YkImage: typeof import('@yike-design/ui')['YkImage']
    YkInput: typeof import('@yike-design/ui')['YkInput']
    YkPagination: typeof import('@yike-design/ui')['YkPagination']
    YkRadio: typeof import('@yike-design/ui')['YkRadio']
    YkRadioGroup: typeof import('@yike-design/ui')['YkRadioGroup']
    YkSlider: typeof import('@yike-design/ui')['YkSlider']
    YkSpace: typeof import('@yike-design/ui')['YkSpace']
    YkTag: typeof import('@yike-design/ui')['YkTag']
    YkText: typeof import('@yike-design/ui')['YkText']
    YkTheme: typeof import('@yike-design/ui')['YkTheme']
    YkTitle: typeof import('@yike-design/ui')['YkTitle']
  }
}
